# Generated by Django 4.0 on 2021-12-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tache', models.CharField(max_length=5)),
                ('time_tache', models.IntegerField()),
                ('predecesseur', models.CharField(max_length=5)),
            ],
        ),
    ]
